config/routes.rb
Rails.application.routes.draw do
  resources :short_urls, only: [:index, :new, :create, :show]

  root to: 'short_urls#new'
  get "/:id", to: "short_urls#show"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/short_url.rb
class ShortUrl < ApplicationRecord
  validates_uniqueness_of :slug
  validates :original_url, presence: true, uniqueness: true,
                           format: URI::DEFAULT_PARSER.make_regexp(%w[http https]),
                           length: {minimum:11, maximum:255}

  before_create :generate_slug

  def generate_slug
    self.slug = SecureRandom.uuid[0..5]
    true
  end

  #we can sanitize the url for better security
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/short_urls_controller.rb
class ShortUrlsController < ApplicationController
  def index
    @short_urls = ShortUrl.order(visits: :desc).limit(100)
  end

  def show
    return render '404', layout: false, status: 404 unless (@short_urls = ShortUrl.find_by(slug: params[:id]))

    @short_urls.update(visits: @short_urls.visits + 1)
    redirect_to @short_urls.original_url
  end

  def new
    @short_url = ShortUrl.new
  end

  def create
    @short_url = ShortUrl.new(short_url_params)

    if @short_url.save
      FetchPageTitleJob.perform_later(@short_url)
      redirect_to root_path, notice: "Your link was shortened to: #{ENV['HOST_URL'] + @short_url.slug}"
    else
      render :new
    end
  end

  private

  def short_url_params
    params.require(:short_url).permit(:original_url)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Shorten Url</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" type="text/css" href="fonts/iconic/css/material-design-iconic-font.css">

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="bg-img1 overlay1 size1 flex-w flex-c-m p-t-55 p-b-55 p-l-15 p-r-15">
      <div class="wsize1">
        <p class="txt-center p-b-23">
          <i class="zmdi zmdi-8tracks cl0 fs-60" style="font-size: 80px;"></i>
        </p>

        <h3 class="l1-txt1 txt-center p-b-22">
          Short links, big results
        </h3>

        <p class="txt-center m2-txt1 p-b-67">
          A URL shortener built with ruby on rails to help you grow and protect your brand.
        </p>

        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/short_urls/404.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">

<title>404 ShortURL Rails</title>

<link href="https://fonts.googleapis.com/css?family=Montserrat:700,900" rel="stylesheet">

<link type="text/css" rel="stylesheet" href="css/font-awesome.min.css" />

<link type="text/css" rel="stylesheet" href="css/style.css" />


<!--[if lt IE 9]>
		  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
		  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
		<![endif]-->
    <style>
    * {
    -webkit-box-sizing: border-box;
    box-sizing:border-box
}

body {
    padding: 0;
    margin:0
}

#notfound {
    position: relative;
    height:100vh
}

#notfound .notfound-bg {
    position: absolute;
    width: 100%;
    height: 100%;
    background-image: url(../img/bg.jpg);
    background-size:cover
}

#notfound .notfound-bg:after {
    content: '';
    position: absolute;
    width: 100%;
    height: 100%;
    background-color:rgba(255, 0, 36, .7)
}

#notfound .notfound {
    position: absolute;
    left: 50%;
    top: 50%;
    -webkit-transform: translate(-50%, -50%);
    -ms-transform: translate(-50%, -50%);
    transform:translate(-50%, -50%)
}

.notfound {
    max-width: 910px;
    width: 100%;
    line-height: 1.4;
    text-align:center
}

.notfound .notfound-404 {
    position: relative;
    height:200px
}

.notfound .notfound-404 h1 {
    font-family: montserrat, sans-serif;
    position: absolute;
    left: 50%;
    top: 50%;
    -webkit-transform: translate(-50%, -50%);
    -ms-transform: translate(-50%, -50%);
    transform: translate(-50%, -50%);
    font-size: 220px;
    font-weight: 900;
    margin: 0;
    color: #fff;
    text-transform: uppercase;
    letter-spacing:10px
}

.notfound h2 {
    font-family: montserrat, sans-serif;
    font-size: 22px;
    font-weight: 700;
    text-transform: uppercase;
    color: #fff;
    margin-top: 20px;
    margin-bottom:15px
}

.notfound .home-btn, .notfound .contact-btn {
    font-family: montserrat, sans-serif;
    display: inline-block;
    font-weight: 700;
    text-decoration: none;
    background-color: transparent;
    border: 2px solid transparent;
    text-transform: uppercase;
    padding: 13px 25px;
    font-size: 18px;
    border-radius: 40px;
    margin: 7px;
    -webkit-transition: .2s all;
    transition:.2s all
}

.notfound .home-btn:hover, .notfound .contact-btn:hover {
    opacity:.9
}

.notfound .home-btn {
    color: rgba(255, 0, 36, .7);
    background:#fff
}

.notfound .contact-btn {
    border: 2px solid rgba(255, 255, 255, .9);
    color:rgba(255, 255, 255, .9)
}

.notfound-social {
    margin-top:25px
}

.notfound-social > a {
    display: inline-block;
    height: 40px;
    line-height: 40px;
    width: 40px;
    font-size: 14px;
    color: rgba(255, 255, 255, .9);
    margin: 0 6px;
    -webkit-transition: .2s all;
    transition:.2s all
}

.notfound-social > a:hover {
    color: rgba(255, 0, 36, .7);
    background-color: #fff;
    border-radius:50%
}

@media only screen and (max-width: 767px) {
    .notfound .notfound-404 h1 {
        font-size:182px
    }
}

@media only screen and (max-width: 480px) {
    .notfound .notfound-404 {
        height:146px
    }

    .notfound .notfound-404 h1 {
        font-size:146px
    }

    .notfound h2 {
        font-size:16px
    }

    .notfound .home-btn, .notfound .contact-btn {
        font-size: 14px
    }
}


    </style>
</head>
<body>
<div id="notfound">
<div class="notfound-bg"></div>
<div class="notfound">
<div class="notfound-404">
<h1>404</h1>
</div>
<h2>we are sorry, but the page you requested was not found</h2>
<a href="<%= root_path %>" class="home-btn">Go Home</a>
</div>
</div>

<script async src="https://www.googletagmanager.com/gtag/js?id=UA-23581568-13"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-23581568-13');
</script>
</body>
</html>

app/views/short_urls/index.html.erb
<div style="color: white;">
  <p id="notice"><%= notice %></p>

  <h1 style="txt-center m2-txt1">Most Viewed links</h1>
  <table class="table">
    <thead>
      <tr>
        <th>Link</th>
        <th>Title</th>
        <th>Visits</th>
      </tr>
    </thead>
    <tbody>
      <% @short_urls.each do |short_url| %>
        <tr>
          <td><%= ENV['HOST_URL'] + short_url.slug %></td>
          <td><%= short_url.title %></td>
          <td><%= short_url.visits %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<br>

<%= link_to 'Go to Homepage', root_path, class: "flex-c-m s1-txt1 size2 how-btn trans-04 where1" %>

app/views/short_urls/new.html.erb
<%= form_with(model: @short_url, local: true, class: "flex-w flex-c-m contact100-form p-t-70") do |form| %>
  <% if @short_url.errors.any? %>
    <div id="error_explanation" style="color: red;">
      <h2> <i class="zmdi zmdi-alert-triangle"></i> This URL could not be shortened due to <%= pluralize(@short_url.errors.count, "error") %> </h2>

      <ul>
        <% @short_url.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="wrap-input100 validate-input where1">
    <%= form.text_field :original_url, class: "s1-txt1 placeholder0 input100", placeholder: "Your URL..." %>
  </div>
  <div class="control">
      <%= form.submit "Shorten", class: "flex-c-m s1-txt1 size2 how-btn trans-04 where1" %>
  </div>
  <p id="notice" class="txt-center m2-txt1 p-b-67"><%= notice %></p>
  <%= link_to 'See the most visited pages', short_urls_path, class: "flex-c-m s1-txt1 size2 trans-04 where1" %>
<% end %>